/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AmazonesRouteImport } from './routes/amazones'
import { Route as IndexRouteImport } from './routes/index'

const AmazonesRoute = AmazonesRouteImport.update({
  id: '/amazones',
  path: '/amazones',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amazones': typeof AmazonesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/amazones': typeof AmazonesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/amazones': typeof AmazonesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/amazones'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/amazones'
  id: '__root__' | '/' | '/amazones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmazonesRoute: typeof AmazonesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/amazones': {
      id: '/amazones'
      path: '/amazones'
      fullPath: '/amazones'
      preLoaderRoute: typeof AmazonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmazonesRoute: AmazonesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
